const fs = require('fs');
const path = require('path');

const pagesDir = path.join(__dirname, 'src', 'pages');
const files = fs.readdirSync(pagesDir).filter(f => f.endsWith('.tsx'));

for (const file of files) {
  const filePath = path.join(pagesDir, file);
  let content = fs.readFileSync(filePath, 'utf8');

  // Regex to match the bindings block:
  // "        // Bindings generated by script\n"
  // followed by any number of "        if (typeof window !== "undefined") { (window as any).X = Y; }\n" lines
  
  const blockRegex = /\s*\/\/ Bindings generated by script\s*(?:if\s*\(typeof window !== "undefined"\)\s*\{[^\}]+\}\s*)+/g;
  
  if (blockRegex.test(content)) {
    const newContent = content.replace(blockRegex, '');
    fs.writeFileSync(filePath, newContent, 'utf8');
    console.log(`Cleaned ${file}`);
  }
}
